// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/hr/employee/v1/employee.proto

package employeepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EmployeeResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_proto_hr_employee_v1_employee_proto protoreflect.FileDescriptor

const file_proto_hr_employee_v1_employee_proto_rawDesc = "" +
	"\n" +
	"#proto/hr/employee/v1/employee.proto\x12\x0ehr.employee.v1\"$\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x10EmployeeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName2f\n" +
	"\x0fEmployeeService\x12S\n" +
	"\vGetEmployee\x12\".hr.employee.v1.GetEmployeeRequest\x1a .hr.employee.v1.EmployeeResponseB2Z0coraflow-erp-api/proto/hr/employee/v1;employeepbb\x06proto3"

var (
	file_proto_hr_employee_v1_employee_proto_rawDescOnce sync.Once
	file_proto_hr_employee_v1_employee_proto_rawDescData []byte
)

func file_proto_hr_employee_v1_employee_proto_rawDescGZIP() []byte {
	file_proto_hr_employee_v1_employee_proto_rawDescOnce.Do(func() {
		file_proto_hr_employee_v1_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_employee_v1_employee_proto_rawDesc), len(file_proto_hr_employee_v1_employee_proto_rawDesc)))
	})
	return file_proto_hr_employee_v1_employee_proto_rawDescData
}

var file_proto_hr_employee_v1_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hr_employee_v1_employee_proto_goTypes = []any{
	(*GetEmployeeRequest)(nil), // 0: hr.employee.v1.GetEmployeeRequest
	(*EmployeeResponse)(nil),   // 1: hr.employee.v1.EmployeeResponse
}
var file_proto_hr_employee_v1_employee_proto_depIdxs = []int32{
	0, // 0: hr.employee.v1.EmployeeService.GetEmployee:input_type -> hr.employee.v1.GetEmployeeRequest
	1, // 1: hr.employee.v1.EmployeeService.GetEmployee:output_type -> hr.employee.v1.EmployeeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hr_employee_v1_employee_proto_init() }
func file_proto_hr_employee_v1_employee_proto_init() {
	if File_proto_hr_employee_v1_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_employee_v1_employee_proto_rawDesc), len(file_proto_hr_employee_v1_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_employee_v1_employee_proto_goTypes,
		DependencyIndexes: file_proto_hr_employee_v1_employee_proto_depIdxs,
		MessageInfos:      file_proto_hr_employee_v1_employee_proto_msgTypes,
	}.Build()
	File_proto_hr_employee_v1_employee_proto = out.File
	file_proto_hr_employee_v1_employee_proto_goTypes = nil
	file_proto_hr_employee_v1_employee_proto_depIdxs = nil
}
