// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/hr/employee/v1/employee.proto

package employeepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EmployeeResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EmployeeResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type ListEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*EmployeeResponse    `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeeResponse) Reset() {
	*x = ListEmployeeResponse{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeeResponse) ProtoMessage() {}

func (x *ListEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeeResponse.ProtoReflect.Descriptor instead.
func (*ListEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{1}
}

func (x *ListEmployeeResponse) GetEmployees() []*EmployeeResponse {
	if x != nil {
		return x.Employees
	}
	return nil
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmployeeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmployeeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeeRequest) Reset() {
	*x = ListEmployeeRequest{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeeRequest) ProtoMessage() {}

func (x *ListEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeeRequest.ProtoReflect.Descriptor instead.
func (*ListEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{4}
}

func (x *ListEmployeeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEmployeeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeResponse) Reset() {
	*x = DeleteEmployeeResponse{}
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeResponse) ProtoMessage() {}

func (x *DeleteEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_employee_v1_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_employee_v1_employee_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEmployeeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_hr_employee_v1_employee_proto protoreflect.FileDescriptor

const file_proto_hr_employee_v1_employee_proto_rawDesc = "" +
	"\n" +
	"#proto/hr/employee/v1/employee.proto\x12\x0ehr.employee.v1\"{\n" +
	"\x10EmployeeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"V\n" +
	"\x14ListEmployeeResponse\x12>\n" +
	"\temployees\x18\x01 \x03(\v2 .hr.employee.v1.EmployeeResponseR\temployees\"p\n" +
	"\x15CreateEmployeeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"A\n" +
	"\x12GetEmployeeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x13ListEmployeeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"D\n" +
	"\x15DeleteEmployeeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x16DeleteEmployeeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfd\x02\n" +
	"\x0fEmployeeService\x12Y\n" +
	"\x0eCreateEmployee\x12%.hr.employee.v1.CreateEmployeeRequest\x1a .hr.employee.v1.EmployeeResponse\x12S\n" +
	"\vGetEmployee\x12\".hr.employee.v1.GetEmployeeRequest\x1a .hr.employee.v1.EmployeeResponse\x12Y\n" +
	"\fListEmployee\x12#.hr.employee.v1.ListEmployeeRequest\x1a$.hr.employee.v1.ListEmployeeResponse\x12_\n" +
	"\x0eDeleteEmployee\x12%.hr.employee.v1.DeleteEmployeeRequest\x1a&.hr.employee.v1.DeleteEmployeeResponseB2Z0coraflow-erp-api/proto/hr/employee/v1;employeepbb\x06proto3"

var (
	file_proto_hr_employee_v1_employee_proto_rawDescOnce sync.Once
	file_proto_hr_employee_v1_employee_proto_rawDescData []byte
)

func file_proto_hr_employee_v1_employee_proto_rawDescGZIP() []byte {
	file_proto_hr_employee_v1_employee_proto_rawDescOnce.Do(func() {
		file_proto_hr_employee_v1_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_employee_v1_employee_proto_rawDesc), len(file_proto_hr_employee_v1_employee_proto_rawDesc)))
	})
	return file_proto_hr_employee_v1_employee_proto_rawDescData
}

var file_proto_hr_employee_v1_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_hr_employee_v1_employee_proto_goTypes = []any{
	(*EmployeeResponse)(nil),       // 0: hr.employee.v1.EmployeeResponse
	(*ListEmployeeResponse)(nil),   // 1: hr.employee.v1.ListEmployeeResponse
	(*CreateEmployeeRequest)(nil),  // 2: hr.employee.v1.CreateEmployeeRequest
	(*GetEmployeeRequest)(nil),     // 3: hr.employee.v1.GetEmployeeRequest
	(*ListEmployeeRequest)(nil),    // 4: hr.employee.v1.ListEmployeeRequest
	(*DeleteEmployeeRequest)(nil),  // 5: hr.employee.v1.DeleteEmployeeRequest
	(*DeleteEmployeeResponse)(nil), // 6: hr.employee.v1.DeleteEmployeeResponse
}
var file_proto_hr_employee_v1_employee_proto_depIdxs = []int32{
	0, // 0: hr.employee.v1.ListEmployeeResponse.employees:type_name -> hr.employee.v1.EmployeeResponse
	2, // 1: hr.employee.v1.EmployeeService.CreateEmployee:input_type -> hr.employee.v1.CreateEmployeeRequest
	3, // 2: hr.employee.v1.EmployeeService.GetEmployee:input_type -> hr.employee.v1.GetEmployeeRequest
	4, // 3: hr.employee.v1.EmployeeService.ListEmployee:input_type -> hr.employee.v1.ListEmployeeRequest
	5, // 4: hr.employee.v1.EmployeeService.DeleteEmployee:input_type -> hr.employee.v1.DeleteEmployeeRequest
	0, // 5: hr.employee.v1.EmployeeService.CreateEmployee:output_type -> hr.employee.v1.EmployeeResponse
	0, // 6: hr.employee.v1.EmployeeService.GetEmployee:output_type -> hr.employee.v1.EmployeeResponse
	1, // 7: hr.employee.v1.EmployeeService.ListEmployee:output_type -> hr.employee.v1.ListEmployeeResponse
	6, // 8: hr.employee.v1.EmployeeService.DeleteEmployee:output_type -> hr.employee.v1.DeleteEmployeeResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hr_employee_v1_employee_proto_init() }
func file_proto_hr_employee_v1_employee_proto_init() {
	if File_proto_hr_employee_v1_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_employee_v1_employee_proto_rawDesc), len(file_proto_hr_employee_v1_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_employee_v1_employee_proto_goTypes,
		DependencyIndexes: file_proto_hr_employee_v1_employee_proto_depIdxs,
		MessageInfos:      file_proto_hr_employee_v1_employee_proto_msgTypes,
	}.Build()
	File_proto_hr_employee_v1_employee_proto = out.File
	file_proto_hr_employee_v1_employee_proto_goTypes = nil
	file_proto_hr_employee_v1_employee_proto_depIdxs = nil
}
