// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tenant/tenant/v1/tenant.proto

package tenantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_tenant_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *InfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_tenant_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_proto_tenant_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_proto_tenant_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"#proto/tenant/tenant/v1/tenant.proto\x12\x10tenant.tenant.v1\"\x1d\n" +
	"\vInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\fInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug2V\n" +
	"\rTenantService\x12E\n" +
	"\x04Info\x12\x1d.tenant.tenant.v1.InfoRequest\x1a\x1e.tenant.tenant.v1.InfoResponseB2Z0coraflow-erp-api/proto/tenant/tenant/v1;tenantpbb\x06proto3"

var (
	file_proto_tenant_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_proto_tenant_tenant_v1_tenant_proto_rawDescData []byte
)

func file_proto_tenant_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_proto_tenant_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_proto_tenant_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tenant_tenant_v1_tenant_proto_rawDesc), len(file_proto_tenant_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_proto_tenant_tenant_v1_tenant_proto_rawDescData
}

var file_proto_tenant_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tenant_tenant_v1_tenant_proto_goTypes = []any{
	(*InfoRequest)(nil),  // 0: tenant.tenant.v1.InfoRequest
	(*InfoResponse)(nil), // 1: tenant.tenant.v1.InfoResponse
}
var file_proto_tenant_tenant_v1_tenant_proto_depIdxs = []int32{
	0, // 0: tenant.tenant.v1.TenantService.Info:input_type -> tenant.tenant.v1.InfoRequest
	1, // 1: tenant.tenant.v1.TenantService.Info:output_type -> tenant.tenant.v1.InfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tenant_tenant_v1_tenant_proto_init() }
func file_proto_tenant_tenant_v1_tenant_proto_init() {
	if File_proto_tenant_tenant_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tenant_tenant_v1_tenant_proto_rawDesc), len(file_proto_tenant_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tenant_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_proto_tenant_tenant_v1_tenant_proto_depIdxs,
		MessageInfos:      file_proto_tenant_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_proto_tenant_tenant_v1_tenant_proto = out.File
	file_proto_tenant_tenant_v1_tenant_proto_goTypes = nil
	file_proto_tenant_tenant_v1_tenant_proto_depIdxs = nil
}
