// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/hr/department/v1/department.proto

package departmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsRequest) Reset() {
	*x = ListDepartmentsRequest{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsRequest) ProtoMessage() {}

func (x *ListDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{0}
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{1}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse) Reset() {
	*x = ListDepartmentsResponse{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse) ProtoMessage() {}

func (x *ListDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{2}
}

func (x *ListDepartmentsResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

var File_proto_hr_department_v1_department_proto protoreflect.FileDescriptor

const file_proto_hr_department_v1_department_proto_rawDesc = "" +
	"\n" +
	"'proto/hr/department/v1/department.proto\x12\x10hr.department.v1\"\x18\n" +
	"\x16ListDepartmentsRequest\"0\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Y\n" +
	"\x17ListDepartmentsResponse\x12>\n" +
	"\vdepartments\x18\x01 \x03(\v2\x1c.hr.department.v1.DepartmentR\vdepartments2{\n" +
	"\x11DepartmentService\x12f\n" +
	"\x0fListDepartments\x12(.hr.department.v1.ListDepartmentsRequest\x1a).hr.department.v1.ListDepartmentsResponseB6Z4coraflow-erp-api/proto/hr/department/v1;departmentpbb\x06proto3"

var (
	file_proto_hr_department_v1_department_proto_rawDescOnce sync.Once
	file_proto_hr_department_v1_department_proto_rawDescData []byte
)

func file_proto_hr_department_v1_department_proto_rawDescGZIP() []byte {
	file_proto_hr_department_v1_department_proto_rawDescOnce.Do(func() {
		file_proto_hr_department_v1_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_department_v1_department_proto_rawDesc), len(file_proto_hr_department_v1_department_proto_rawDesc)))
	})
	return file_proto_hr_department_v1_department_proto_rawDescData
}

var file_proto_hr_department_v1_department_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_hr_department_v1_department_proto_goTypes = []any{
	(*ListDepartmentsRequest)(nil),  // 0: hr.department.v1.ListDepartmentsRequest
	(*Department)(nil),              // 1: hr.department.v1.Department
	(*ListDepartmentsResponse)(nil), // 2: hr.department.v1.ListDepartmentsResponse
}
var file_proto_hr_department_v1_department_proto_depIdxs = []int32{
	1, // 0: hr.department.v1.ListDepartmentsResponse.departments:type_name -> hr.department.v1.Department
	0, // 1: hr.department.v1.DepartmentService.ListDepartments:input_type -> hr.department.v1.ListDepartmentsRequest
	2, // 2: hr.department.v1.DepartmentService.ListDepartments:output_type -> hr.department.v1.ListDepartmentsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hr_department_v1_department_proto_init() }
func file_proto_hr_department_v1_department_proto_init() {
	if File_proto_hr_department_v1_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_department_v1_department_proto_rawDesc), len(file_proto_hr_department_v1_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_department_v1_department_proto_goTypes,
		DependencyIndexes: file_proto_hr_department_v1_department_proto_depIdxs,
		MessageInfos:      file_proto_hr_department_v1_department_proto_msgTypes,
	}.Build()
	File_proto_hr_department_v1_department_proto = out.File
	file_proto_hr_department_v1_department_proto_goTypes = nil
	file_proto_hr_department_v1_department_proto_depIdxs = nil
}
