// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/hr/department/v1/department.proto

package departmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentResponse) Reset() {
	*x = DepartmentResponse{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentResponse) ProtoMessage() {}

func (x *DepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentResponse.ProtoReflect.Descriptor instead.
func (*DepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{0}
}

func (x *DepartmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartmentResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DepartmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*DepartmentResponse  `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentResponse) Reset() {
	*x = ListDepartmentResponse{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentResponse) ProtoMessage() {}

func (x *ListDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{1}
}

func (x *ListDepartmentResponse) GetDepartments() []*DepartmentResponse {
	if x != nil {
		return x.Departments
	}
	return nil
}

type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDepartmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepartmentRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepartmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentRequest) Reset() {
	*x = ListDepartmentRequest{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentRequest) ProtoMessage() {}

func (x *ListDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{4}
}

func (x *ListDepartmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDepartmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_department_v1_department_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_department_v1_department_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDepartmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_hr_department_v1_department_proto protoreflect.FileDescriptor

const file_proto_hr_department_v1_department_proto_rawDesc = "" +
	"\n" +
	"'proto/hr/department/v1/department.proto\x12\x10hr.department.v1\"U\n" +
	"\x12DepartmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"`\n" +
	"\x16ListDepartmentResponse\x12F\n" +
	"\vdepartments\x18\x01 \x03(\v2$.hr.department.v1.DepartmentResponseR\vdepartments\"z\n" +
	"\x17CreateDepartmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"C\n" +
	"\x14GetDepartmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"4\n" +
	"\x15ListDepartmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"F\n" +
	"\x17DeleteDepartmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"4\n" +
	"\x18DeleteDepartmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa7\x03\n" +
	"\x11DepartmentService\x12c\n" +
	"\x10CreateDepartment\x12).hr.department.v1.CreateDepartmentRequest\x1a$.hr.department.v1.DepartmentResponse\x12]\n" +
	"\rGetDepartment\x12&.hr.department.v1.GetDepartmentRequest\x1a$.hr.department.v1.DepartmentResponse\x12c\n" +
	"\x0eListDepartment\x12'.hr.department.v1.ListDepartmentRequest\x1a(.hr.department.v1.ListDepartmentResponse\x12i\n" +
	"\x10DeleteDepartment\x12).hr.department.v1.DeleteDepartmentRequest\x1a*.hr.department.v1.DeleteDepartmentResponseB6Z4coraflow-erp-api/proto/hr/department/v1;departmentpbb\x06proto3"

var (
	file_proto_hr_department_v1_department_proto_rawDescOnce sync.Once
	file_proto_hr_department_v1_department_proto_rawDescData []byte
)

func file_proto_hr_department_v1_department_proto_rawDescGZIP() []byte {
	file_proto_hr_department_v1_department_proto_rawDescOnce.Do(func() {
		file_proto_hr_department_v1_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_department_v1_department_proto_rawDesc), len(file_proto_hr_department_v1_department_proto_rawDesc)))
	})
	return file_proto_hr_department_v1_department_proto_rawDescData
}

var file_proto_hr_department_v1_department_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_hr_department_v1_department_proto_goTypes = []any{
	(*DepartmentResponse)(nil),       // 0: hr.department.v1.DepartmentResponse
	(*ListDepartmentResponse)(nil),   // 1: hr.department.v1.ListDepartmentResponse
	(*CreateDepartmentRequest)(nil),  // 2: hr.department.v1.CreateDepartmentRequest
	(*GetDepartmentRequest)(nil),     // 3: hr.department.v1.GetDepartmentRequest
	(*ListDepartmentRequest)(nil),    // 4: hr.department.v1.ListDepartmentRequest
	(*DeleteDepartmentRequest)(nil),  // 5: hr.department.v1.DeleteDepartmentRequest
	(*DeleteDepartmentResponse)(nil), // 6: hr.department.v1.DeleteDepartmentResponse
}
var file_proto_hr_department_v1_department_proto_depIdxs = []int32{
	0, // 0: hr.department.v1.ListDepartmentResponse.departments:type_name -> hr.department.v1.DepartmentResponse
	2, // 1: hr.department.v1.DepartmentService.CreateDepartment:input_type -> hr.department.v1.CreateDepartmentRequest
	3, // 2: hr.department.v1.DepartmentService.GetDepartment:input_type -> hr.department.v1.GetDepartmentRequest
	4, // 3: hr.department.v1.DepartmentService.ListDepartment:input_type -> hr.department.v1.ListDepartmentRequest
	5, // 4: hr.department.v1.DepartmentService.DeleteDepartment:input_type -> hr.department.v1.DeleteDepartmentRequest
	0, // 5: hr.department.v1.DepartmentService.CreateDepartment:output_type -> hr.department.v1.DepartmentResponse
	0, // 6: hr.department.v1.DepartmentService.GetDepartment:output_type -> hr.department.v1.DepartmentResponse
	1, // 7: hr.department.v1.DepartmentService.ListDepartment:output_type -> hr.department.v1.ListDepartmentResponse
	6, // 8: hr.department.v1.DepartmentService.DeleteDepartment:output_type -> hr.department.v1.DeleteDepartmentResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hr_department_v1_department_proto_init() }
func file_proto_hr_department_v1_department_proto_init() {
	if File_proto_hr_department_v1_department_proto != nil {
		return
	}
	file_proto_hr_department_v1_department_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_department_v1_department_proto_rawDesc), len(file_proto_hr_department_v1_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_department_v1_department_proto_goTypes,
		DependencyIndexes: file_proto_hr_department_v1_department_proto_depIdxs,
		MessageInfos:      file_proto_hr_department_v1_department_proto_msgTypes,
	}.Build()
	File_proto_hr_department_v1_department_proto = out.File
	file_proto_hr_department_v1_department_proto_goTypes = nil
	file_proto_hr_department_v1_department_proto_depIdxs = nil
}
