// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    id,
    tenant_id,
    name,
    parent_id
)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, parent_id, created_at
`

type CreateDepartmentParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	ParentID *uuid.UUID
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ParentID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE tenant_id = $1
AND id = $2
`

type DeleteDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.TenantID, arg.ID)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, tenant_id, name, parent_id, created_at
FROM departments
WHERE tenant_id = $1
AND id = $2
`

type GetDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.TenantID, arg.ID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const listChildDepartment = `-- name: ListChildDepartment :many
SELECT id, tenant_id, name, parent_id, created_at
FROM departments
WHERE tenant_id = $1
AND parent_id = $2
ORDER BY created_at DESC
`

type ListChildDepartmentParams struct {
	TenantID uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) ListChildDepartment(ctx context.Context, arg ListChildDepartmentParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, listChildDepartment, arg.TenantID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartment = `-- name: ListDepartment :many
SELECT id, tenant_id, name, parent_id, created_at
FROM departments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepartment(ctx context.Context, tenantID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartment, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDepartment = `-- name: ListRootDepartment :many
SELECT id, tenant_id, name, parent_id, created_at
FROM departments
WHERE tenant_id = $1
AND parent_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRootDepartment(ctx context.Context, tenantID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listRootDepartment, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $3,
    parent_id = $4
WHERE tenant_id = $1
AND id = $2
RETURNING id, tenant_id, name, parent_id, created_at
`

type UpdateDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Name     string
	ParentID *uuid.UUID
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.ParentID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}
