// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    id,
    tenant_id,
    user_id,
    first_name,
    last_name,
    department_id,
    manager_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
`

type CreateEmployeeParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       *uuid.UUID
	FirstName    string
	LastName     string
	DepartmentID *uuid.UUID
	ManagerID    *uuid.UUID
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DepartmentID,
		arg.ManagerID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE tenant_id = $1
AND id = $2
`

type DeleteEmployeeParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteEmployee, arg.TenantID, arg.ID)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
FROM employees
WHERE tenant_id = $1
AND id = $2
`

type GetEmployeeParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.TenantID, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByUser = `-- name: GetEmployeeByUser :one
SELECT id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
FROM employees
WHERE tenant_id = $1
AND user_id = $2
`

type GetEmployeeByUserParams struct {
	TenantID uuid.UUID
	UserID   *uuid.UUID
}

func (q *Queries) GetEmployeeByUser(ctx context.Context, arg GetEmployeeByUserParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUser, arg.TenantID, arg.UserID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployee = `-- name: ListEmployee :many
SELECT id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
FROM employees
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEmployee(ctx context.Context, tenantID uuid.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployee, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentID,
			&i.ManagerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeByDepartment = `-- name: ListEmployeeByDepartment :many
SELECT id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
FROM employees
WHERE tenant_id = $1
AND department_id = $2
ORDER BY created_at DESC
`

type ListEmployeeByDepartmentParams struct {
	TenantID     uuid.UUID
	DepartmentID *uuid.UUID
}

func (q *Queries) ListEmployeeByDepartment(ctx context.Context, arg ListEmployeeByDepartmentParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeeByDepartment, arg.TenantID, arg.DepartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentID,
			&i.ManagerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeByManager = `-- name: ListEmployeeByManager :many
SELECT id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
FROM employees
WHERE tenant_id = $1
AND manager_id = $2
ORDER BY created_at DESC
`

type ListEmployeeByManagerParams struct {
	TenantID  uuid.UUID
	ManagerID *uuid.UUID
}

func (q *Queries) ListEmployeeByManager(ctx context.Context, arg ListEmployeeByManagerParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeeByManager, arg.TenantID, arg.ManagerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentID,
			&i.ManagerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET first_name = $3,
    last_name = $4,
    department_id = $5,
    manager_id = $6
WHERE tenant_id = $1
AND id = $2
RETURNING id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
`

type UpdateEmployeeParams struct {
	TenantID     uuid.UUID
	ID           uuid.UUID
	FirstName    string
	LastName     string
	DepartmentID *uuid.UUID
	ManagerID    *uuid.UUID
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.TenantID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DepartmentID,
		arg.ManagerID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}

const updateEmployeeManager = `-- name: UpdateEmployeeManager :one
UPDATE employees
SET manager_id = $3
WHERE tenant_id = $1
AND id = $2
RETURNING id, tenant_id, user_id, first_name, last_name, department_id, manager_id, created_at
`

type UpdateEmployeeManagerParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	ManagerID *uuid.UUID
}

func (q *Queries) UpdateEmployeeManager(ctx context.Context, arg UpdateEmployeeManagerParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeManager, arg.TenantID, arg.ID, arg.ManagerID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.CreatedAt,
	)
	return i, err
}
