// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	ParentID  *uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Employee struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       *uuid.UUID
	FirstName    string
	LastName     string
	DepartmentID *uuid.UUID
	ManagerID    *uuid.UUID
	CreatedAt    pgtype.Timestamptz
}
