// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}
