// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    tenant_id,
    is_internal
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, tenant_id, is_internal, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	TenantID     *uuid.UUID
	IsInternal   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.TenantID,
		arg.IsInternal,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TenantID,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, tenant_id, is_internal, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TenantID,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, tenant_id, is_internal, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TenantID,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInternalUser = `-- name: ListInternalUser :many
SELECT id, email, password_hash, tenant_id, is_internal, created_at, updated_at
FROM users
WHERE is_internal = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListInternalUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listInternalUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.TenantID,
			&i.IsInternal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserByTenant = `-- name: ListUserByTenant :many
SELECT id, email, password_hash, tenant_id, is_internal, created_at, updated_at
FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserByTenant(ctx context.Context, tenantID *uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUserByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.TenantID,
			&i.IsInternal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTenant = `-- name: UpdateUserTenant :one
UPDATE users
SET tenant_id = $2
WHERE id = $1
RETURNING id, email, password_hash, tenant_id, is_internal, created_at, updated_at
`

type UpdateUserTenantParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) UpdateUserTenant(ctx context.Context, arg UpdateUserTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTenant, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TenantID,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
